verson: 0.0
os: linux
files:
        - source: helloworld.js
          destination: /usr/local/helloworld/
        - source: scripts/helloworld.conf
          destination: /etc/init/
hooks:
        BeforeInstall:
                - location: scripts/stop.sh
                  timeout: 10
        AllicationStart:
                - location: scripts/start.sh
                  timeout: 10
        ValidateService:
                - location: scripts/validate.sh

